DONADORESYENTIDADES = https://donadoresyentidades-hxss.onrender.com
DONACIONES = https://donaciones-1-7xzd.onrender.com
INCENTIVOS = https://entrega-2-lseijasferraudo.onrender.com
LOGISTICA = https://entrega-2-lseijasferraudo.onrender.com

NAME_BOT = UTNBA_DDS_K3003_GRUPO7
TOKEN_BOT = 8837514281:AAEXk0x6H8w8ww9rWSpUSXiEzrA6_yOiPZY